name: Build and Push Docker Image

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
                  username: ${{ secrets.AZURE_ACR_USERNAME }}
                  password: ${{ secrets.AZURE_ACR_PASSWORD }}

            - name: Build and push Docker image to ACR
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi-image:${{ github.sha }}
                      ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi-image:latest

            # - name: Login to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #       username: ${{ secrets.DOCKERHUB_USERNAME }}
            #       password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - name: Build and push Docker image to Docker Hub
            #   uses: docker/build-push-action@v4
            #   with:
            #       push: true
            #       tags: |
            #           bibishanpandey/devops-exercise3:${{ github.sha }}
            #           ${{ format('bibishanpandey/devops-exercise3:{0}', github.ref == 'refs/heads/master' && 'latest' || 'nightly') }}
