name: Terraform Iac and AKS Deployment

on:
    workflow_run:
        workflows:
            - "Build and Push Docker Image"
        types:
            - completed
        paths:
            - "**/*.tf"

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.0

            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
                  username: ${{ secrets.AZURE_ACR_USERNAME }}
                  password: ${{ secrets.AZURE_ACR_PASSWORD }}

            - name: Terraform Init
              run: terraform init

            - name: Import Existing Resource Group
              run: |
                  terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/fastapi-rg
              continue-on-error: true # Prevent failure if resource is already managed

            - name: Terraform Apply
              env:
                  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
              run: terraform apply -auto-approve
              continue-on-error: true

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
                  username: ${{ secrets.AZURE_ACR_USERNAME }}
                  password: ${{ secrets.AZURE_ACR_PASSWORD }}

            - name: Run kubectl to apply latest deployment
              run: |
                  az aks get-credentials --resource-group fastapi-rg --name fastapi-aks
                  kubectl set image deployment/fastapi fastapi=${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi:latest
